sensors:
 url[0] : '192.168.201.11'
 url[1] : '192.168.201.12'
 url[2] : '192.168.201.13'
 url[3] : '192.168.201.14'
 url[4] : '192.168.201.15'



spring:
    datasource:
        username: admin
        password: {cipher}7401c67e70e456abf55db43f2a7de85b28c8ad6545b8de970f28f51a81c62c88
        url: jdbc:postgresql://localhost:5432/home
        driverClassName: org.postgresql.Driver

management:
   endpoints:
          web:
            exposure:
                    include: "*"
          enabled-by-default: true
